name: Check Starter Projects

on:
    pull_request:
      types: [ opened, synchronize ]
      branches:
        - 'release-*'
    push:
      paths:
        - 'samples/starter-projects/**'

jobs:
  konsist-starter-android-gradle-groovy-junit-4:
    name: Konsist Starter Android Gradle Groovy Junit 4
    runs-on: ubuntu-latest
    steps:

      - name: Publish Konsist Artifact To Local Maven Repository
        run: echo DOne
